server:
  port: 8002

api-gateshield:
  address: http://192.168.31.68:8001  # 注册中心；从这里获取接口信息以及完成注册网关操作;所填为注册中心所在的主机ip
  groupId: 10001                      # 网关分组；每一个网关通信组件都分配一个对应的分组
  gatewayId: api-gateway-g4           # 网关标识；
  gatewayName: 电商配送网关             # 网关名称；
  gatewayAddress: 192.168.31.68:7397  # 网关服务；网关的通信服务Netty启动时使用IP和端口;RPC服务提供者所在的主机IP